# Generated by Django 5.0.7 on 2024-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
